- hosts: master
  become: yes
  tasks:
    - name: install helm
      become: yes
      become_user: ubuntu
      shell: curl https://baltocdn.com/helm/signing.asc | sudo apt-key add - && sudo apt-get install apt-transport-https --yes && echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list && sudo apt-get update && sudo apt-get install helm
      args:
        chdir: $HOME
        creates: helm-installed

    - name: changes for MetalLB
      become: yes
      become_user: ubuntu
      shell: kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" |  kubectl apply -f - -n kube-system
      args:
        chdir: $HOME
        creates: metallb-ready

    - name: install MetalLB
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml && kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml && kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
      args:
        chdir: $HOME
        creates: metallb-installed

    - name: install ingress-nginx
      become: yes
      become_user: ubuntu
      shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm install ingress-nginx ingress-nginx/ingress-nginx
      args:
        chdir: $HOME
        creates: ingress-installed
