- hosts: master
  become: yes
  tasks:
    - name: install helm
      become: yes
      become_user: ubuntu
      shell: curl https://baltocdn.com/helm/signing.asc | sudo apt-key add - && sudo apt-get install apt-transport-https --yes && echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list && sudo apt-get update && sudo apt-get install helm
      args:
        chdir: $HOME
        creates: helm-installed

    - name: install ingress-nginx
      become: yes
      become_user: ubuntu
      shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm install ingress-nginx ingress-nginx/ingress-nginx
      args:
        chdir: $HOME
        creates: ingress-installed
